# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "ayu"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "fire"
    statusline_iseparator = "fire"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    filemanager = 'nerdtree'
    filetree_direction = 'left'
    bootstrap_before = 'bootstrap#before'
    bootstrap_after= 'bootstrap#before'

[[layers]]
name='core'
filetree_show_hidden= 'true'

[[layers]]
name = 'default'

[[layers]]
name='ui'
enable_scrollbar= true

[[layers]]
name='core#banner'

[[layers]]
name='github'

[[layers]]
name='git'

[[layers]]
name='VersionControl'

[[layers]]
name='denite'

[[layers]]
name='colorscheme'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'lang#typescript'

[[layers]]
name = 'lang#javascript'

# disable nonsense
[[layers]]
name = 'checkers'
enable = false

# colorizer
[[custom_plugins]]
repo = 'lilydjwg/colorizer'
merged = false

# mf prettier
[[custom_plugins]]
repo='prettier/vim-prettier'
merged = false

# reeeeeeeact
[[custom_plugins]]
repo = 'maxmellon/vim-jsx-pretty'
merged = false

[[custom_plugins]]
repo = 'ryanoasis/vim-devicons'
merged = false


[[custom_plugins]]
repo = 'ayu-theme/ayu-vim'
merged = false
